### ISSUE TITLE
Reservation, User 간의 N + 1 문제 `Fetch Join`을 통한 해결

### ISSUE THREAD

**Issue by esperar** [GSM-MSG/Hi-v2-BackEnd#161]
### Describe

UserRepository`findAllByreservation(reservation: ReservationJpaEntity)`과 같은 메서드들은 N + 1 문제를 야기할 수 있습니다. 솔루션으로는 두가지가 있습니다.

### Query 작성을 통한 해결

```kt
@Query("SELECT u FROM UserJpaEntity u JOIN FETCH u.reservation WHERE u.reservation = :reservation")
fun findAllByReservation(reservation: ReservationJpaEntity): List<UserJpaEntity>
```

<br>

### @EntityGraph 사용
JPA 2.1 부터 추가된 어노테이션으로 fetch join을 쉽게 적용할 수 있도록 도와줍니다.
```kt
@EntityGraph(attributePaths = ["reservation"])
fun findAllByReservation(reservation: ReservationJpaEntity): List<UserJpaEntity>
```

### Additional

batch size 조정은 이미 끝마쳐놓은 상태지만 좀 더 쿼리를 사용한 두 가지 솔루션을 제안해봅니다.

**Comment by JuuuuHong** [comment]
[그리 복잡한 Query가 아닌 것 같기에 ](https://www.inflearn.com/questions/824746/fetchjoin%EC%8B%9C-querydsl%EA%B3%BC-entitygraph-%EC%82%AC%EC%9A%A9-%EA%B8%B0%EC%A4%80)
저도 위 글처럼 Entitygraph로 해결될 문제라면 가독성 측면에서 Entitygraph가 좋다고 생각합니다!
