### ISSUE TITLE
로그인 안됨

### ISSUE THREAD

**Issue by index1207** [GSM-MSG/Hi-v2-BackEnd#268]
### Describe

지금 HI에서 로그인을 하려 하면 원래 화면으로 되돌아와 사용할 수 없습니다.

### Additional

![image](https://github.com/GSM-MSG/Hi-v2-BackEnd/assets/63224377/b1daff91-d054-4d20-b4fd-c02a99f57445)
![image](https://github.com/GSM-MSG/Hi-v2-BackEnd/assets/63224377/53f0428d-c69b-4818-bcab-d44adbbdb46b)

**Comment by kimgh06** [comment]
![image](https://github.com/GSM-MSG/Hi-v2-BackEnd/assets/101877146/f69ecad7-d051-43ac-a247-e527249cf508)

503이라 서버 터진듯요.
빨리 고쳐주세요.
